import Link from 'next/link'
import '../globals.css'
import { Inter } from 'next/font/google'
import { getPages } from '@/sanity/utils/getPages'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Sanity',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    //get all of our pages
    const pages = await getPages()
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-5xl mx-auto px-4 sm:px-12 lg:px-0 py-10`}>
        <header className='flex items-center justify-between' >
            <Link
                href={'/'}
                className='
                    bg-gradient-to-r
                    from-orange-400
                    via-red-500
                    to-purple-600
                    bg-clip-text
                    text-transparent
                    text-lg
                    font-extrabold
                '
            >
                Hello
            </Link>
            <div className='flex items-center gap-3 text-sm text-gray-600'>
                {pages.map((page) => (
                <Link key={page._id} href={`/${page.slug}`} className='hover:underline'>
                    {page.title}
                 </Link>
                ))}
            </div>
        </header>

        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
